### ISSUE TITLE
how to show only few pages from the pdf ?

### ISSUE THREAD

**Issue by sethavi** [Dmitry-Borodin/pdfview-android#13]
if I have pdf of 100 pages and I want to show only page number 5 to 10 programmatically. 

I used [https://github.com/barteksc/AndroidPdfViewer](url)
this library but it is not lightweight and takes more time to open but it had the pages feature 
... can you implement it in your library?

`pdfView.fromAsset("PDFNAME.PDF)
    .pages(0, 2, 1, 7, 10)    .load();`

**Comment by Dmitry-Borodin** [comment]
This is technically doable , while I don't see a big demand for it, I think it's better to just add document with only those few pages to assets if you have this case.
Is there a special need to show different sets of pages from the same document in different cases?
