### ISSUE TITLE
App crashes in landscape mode 

### ISSUE THREAD

**Issue by sethavi** [Dmitry-Borodin/pdfview-android#14]
how to solve this issue ?

**Comment by Dmitry-Borodin** [comment]
Which app? Stacktrace?

**Comment by sethavi** [comment]
app crashes or freezes when the activity containing pdfview is open and mobile screen is rotated to landscape mode.

**Comment by Dmitry-Borodin** [comment]
Just tested sample again - nothing is frozen or crashing. Please provide sample or stacktrace.

**Comment by sethavi** [comment]
yes, it supports landscape mode. I was using a large pdf (8 Mb, 3000+ pages ) and it crashed.

It handles pdf with less size. I tried the small-sized pdf and worked fine. but still, the rendering was laggy. 
any way to improve rendering?

**Comment by Dmitry-Borodin** [comment]
I need to reproduce the issue to see what are the buttlenecks and what can be improved. Please provide sample.

**Comment by sethavi** [comment]
[kll9090.pdf](https://github.com/Dmitry-Borodin/pdfview-android/files/4996045/kll9090.pdf)

I was using this file ...in landscape mode my phone crashes and freezes ..
phone specs - Android P, 4gb ram , 64 internal

**Comment by sethavi** [comment]
any updates ?

**Comment by Dmitry-Borodin** [comment]
Not at the moment.
And you can actually profile this case yourself and came with suggestions of bottlenecks and how to improve situation.
