### ISSUE TITLE
pdf from url - network sample

### ISSUE THREAD

**Issue by Marcosmaliki** [Dmitry-Borodin/pdfview-android#2]
View pdf from url support

**Comment by Marcosmaliki** [comment]
I found a solution. Download the pdf using Fileloader then pass it to pdfView as a file. Awesome library @Dmitry-Borodin.
Sample code:
`FileLoader.with(this)
            .load(url)
            .fromDirectory("PdfFiles", FileLoader.DIR_INTERNAL)
            .asFile( object :FileRequestListener<File> {
                override fun onLoad(request: FileLoadRequest?, response: FileResponse<File>?) {
                   response?.let {
                       val nooFile:File  = response.body
                       pdf_view.fromFile(nooFile).show()
                   }
                }

                override fun onError(request: FileLoadRequest?, t: Throwable?) {

                }
            })`
 I will close this issue now.

**Comment by Dmitry-Borodin** [comment]
Yes, this library doesn't manage downloading part, because then it will have to be aware of life cycle, cashing et.c. and I would like to keep it slim and simple.

**Comment by Dmitry-Borodin** [comment]
You can use any network library to download files.

**Comment by happysingh23828** [comment]
@Dmitry-Borodin can I give you PR for showing pdf using Rx-java and Retrofit for remote?

**Comment by Dmitry-Borodin** [comment]
@happysingh23828 
Adding another sample with downloading would be a good improvement, while I think it's important to not confuse people with solution, that may not work for them.
If you can make sure that file will be downloaded only once (it can be big) despite activity lifecycle and without leaks - please do that.

**Comment by happysingh23828** [comment]
@Dmitry-Borodin  thanks for the quick response. I'll submit the PR asap.

**Comment by happysingh23828** [comment]
@Dmitry-Borodin  Should I give a sample application or add a new feature in the library itself to open pdf from File URL?

**Comment by Dmitry-Borodin** [comment]
Do you mean adding dependency to Rx for this tiny library?
If you know how to handle all the cases mentioned above while keeping lib small - please explain how.
If you want to add a lot of dependencies just to load a file - just add another sample app with lots of extra libraries and showcase how to load pdf before showing it, while properly loading lifestyles and keeping file in cache when it's loaded. 

I would just load it in jetpack "viewmodel" and show how to set cache size for basic http client and mention which flags backend should set so it will be cached. We don't need RX or Retrofit for that through.

**Comment by Dmitry-Borodin** [comment]
Working on a sample in dev branch

**Comment by Dmitry-Borodin** [comment]
https://github.com/Dmitry-Borodin/pdfview-android/tree/master/sample-network
Feel free to reopen issue if there will be questions.
