### ISSUE TITLE
Editable fields not displayed

### ISSUE THREAD

**Issue by AlainBrun** [Dmitry-Borodin/pdfview-android#26]
Hi

I am using a pdf with editable fields, when I use the library all is displayed except the content of editable fields.
Is it possible to patch this behavior?

BR

Alain

PDF with fields:
![2020-12-02_14h56_15](https://user-images.githubusercontent.com/4931516/100881716-91342680-34ae-11eb-9ae0-c24d9d0e9634.png)

Displayed by the library:
![2020-12-02_14h57_57](https://user-images.githubusercontent.com/4931516/100881887-c5a7e280-34ae-11eb-9a7e-a14b3ba8630b.png)

**Comment by Dmitry-Borodin** [comment]
This is a question of why platform [PdfRenderer](https://developer.android.com/reference/kotlin/android/graphics/pdf/PdfRenderer) desn't render them. I'm don't see such limitation mentioned in official docs and don't know any flags of how this can be fixed. 

It definitely will not allow you to type in editable content. If you need to edit pdf, android platform renderer is not enough and you should look at this big libraries that have complete native logic shipped with them.

**Comment by Dmitry-Borodin** [comment]
Closing this one
