### ISSUE TITLE
sunsetting jcenter

### ISSUE THREAD

**Issue by Dmitry-Borodin** [Dmitry-Borodin/pdfview-android#28]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Please provide another way to access the library,

**Comment by Serafin-Lopez** [comment]
Dejo de funcionar Jcenter

**Comment by Dmitry-Borodin** [comment]
Just need to figure out how to sign artifacts on bitrise properly. It will be on maven central.

**Comment by GustavoRoss** [comment]
any update on that?

**Comment by tjdam007** [comment]
Please update it on mavenCentral

**Comment by Dmitry-Borodin** [comment]
Still didn't get it how should I setup deploy on bitrise. Separate key for each library? How to manage backup, how should I upload it and setup onlocking on bitrise et.c.
If somebody have experience - I would gladly listen. Otherwise when there will be bad weather in the Alps will find to time to resolve this.

**Comment by Dmitry-Borodin** [comment]
Current version is available till 2022, dont' worry. The problem is I cannot publish updates.

**Comment by Dmitry-Borodin** [comment]
https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/ another guide
