### ISSUE TITLE
Support for encrypted pdf

### ISSUE THREAD

**Issue by haisiva03** [Dmitry-Borodin/pdfview-android#3]
your library file cannot open password protected file....if i try to open it through exception as java.lang.SecurityException: password required or incorrect password by the way there is no any option to give password.

**Comment by Dmitry-Borodin** [comment]
Password protected files are not supported at the moment. I will check what we can do here.

**Comment by Dmitry-Borodin** [comment]
@haisiva03 Thank you for interest in the project

As far as I see, android PdfRenderer doesn't support password protected files at all.
So I would recommend you to take a look at another libraries that are shipping custom renderer with the library, they are way bigger though.
Something like [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer) or [https://github.com/itext](https://github.com/itext)

This project intended to be very slim and I consider password protected files as an edge case that may be unsupported.
