### ISSUE TITLE
Does this view support loader and crossfade animation

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [Dmitry-Borodin/pdfview-android#34]
Does this view support loader and crossfade animation ?
While the document is being downloaded, does this view support loader and cross fade animation like the library Glide does for images.

**Comment by Dmitry-Borodin** [comment]
This is usual Widget.View and you can animate it.
Library doesn't have out of the box animations like Glide does.
And no plans for implementing those.
Btw it doesn't support downloading. Please read [lib description](https://github.com/Dmitry-Borodin/pdfview-android/blob/master/README.md)

So you can download file and then animate PdfView. But you have to implement it in your app.
