### ISSUE TITLE
pdf is not showing , need help

### ISSUE THREAD

**Issue by ayeshaarshad52** [Dmitry-Borodin/pdfview-android#7]
xml:
<com.pdfview.PDFView
            android:id="@+id/yar"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@id/adView"/>
java:
PDFView pdfView = (PDFView) findViewById(R.id.yar);

        pdfView.fromAsset("book.pdf").show();
i done everything right but my pdf is not displaying it was working before with another library

**Comment by Dmitry-Borodin** [comment]
Please refer to sample in repository, it is working and demonstrates how to use fromAsset()

From this code I can only say that match parent view shouldn't be below another view in the same parent
Different library may have completely different api.
